Admin UI - APIs page
amplication/amplication pull request #1060
Opened 2020-12-24 15:52 UTC by yuval-hazaz

The page is ready before proofreading and before the design.

2020-12-24 19:37 UTC, iddan approved these changes

2020-12-26 08:59 UTC, iddan commented on packages/amplication-data-service-generator/src/admin/app/App.template.tsx
> +          <Route path="/apis-page" component={ApisPage} />
This route is weird

2020-12-26 09:00 UTC, iddan commented on packages/amplication-data-service-generator/src/admin/app/App.template.tsx
> +          <Link to="/pages/api">
This route is weird

2020-12-26 09:00 UTC, iddan requested changes
Please move page to /docs/api or something similar

2020-12-26 09:00 UTC, iddan commented on packages/amplication-data-service-generator/src/admin/app/App.template.tsx
> +            <Route path="/pages/api" component={ApisPage} />
This route is weird

2020-12-30 19:07 UTC, iddan commented on packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
> +          <a href="/graphql" target="graphql">
Should this be Link?

2020-12-30 19:07 UTC, iddan commented on packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
> +          <a href="/api" target="api">
Should this be Link?

2020-12-30 19:29 UTC, yuval-hazaz commented on packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
> +          <a href="/graphql" target="graphql">
yes

2020-12-30 19:30 UTC, yuval-hazaz commented on packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
> +          <a href="/api" target="api">
yes

2020-12-31 13:25 UTC, merged