Update client README and commit generated models
amplication/amplication pull request #1163
Opened 2021-01-20 21:20 UTC by gabrielmoncea

2021-01-21 08:25 UTC, yuval-hazaz requested changes
Please do not include the changes in the package-lock and models.ts in this PR
Please direct the user to the existing instructions document to keep single source

2021-01-21 08:25 UTC, yuval-hazaz commented on packages/amplication-client/README.md
> +Open [http://localhost:3001](http://localhost:3001) to view it in the browser.
Good catch!

2021-01-22 18:43 UTC, gabrielmoncea commented
> Please do not include the changes in the package-lock and models.ts in this PR
> Please direct the user to the existing instructions document to keep single source

Done!

2021-01-23 05:15 UTC, yuval-hazaz approved these changes

2021-01-23 05:15 UTC, merged

2021-01-23 05:16 UTC, yuval-hazaz commented
> > Please do not include the changes in the package-lock and models.ts in this PR
> > Please direct the user to the existing instructions document to keep single source
> 
> Done!

Congrats on your first merge!

2021-07-17 07:37 UTC, yuval-hazaz commented
@all-contributors please add @gabrielmoncea  for code