feat(client/server): Adding unique fields #1493
amplication/amplication pull request #1615
Opened 2021-07-15 14:26 UTC by lalit8347

Open #1493

Added ToggleField for unique option in amplication-client
Corresponding changes to graphql queries for unique option at server and client side.
Added unique option in EntityField model at server side.

2021-07-16 07:00 UTC, yuval-hazaz reviewed
before I continue with the review please revert the changes in the versions of the packages (lerna, and @graphql-codegen/cli).

I do not expect to see any changes in the packge.json or pakcage-lock.json as part of this PR

2021-07-16 11:38 UTC, lalit8347 commented on package.json
> +    "lerna": "^4.0.0"
I might have updated it while installing packages.

2021-07-16 11:38 UTC, lalit8347 commented on packages/amplication-cli/src/models.ts
> +export type MakeOptional<T, K extends keyof T> = Omit<T, K> &
Yeah I agree, I will revert it in next PR.

2021-07-16 11:39 UTC, lalit8347 commented on package.json
> +    "@graphql-codegen/cli": "^1.21.4",
I am not sure about how this is changed, but I will revert it back.

2021-07-17 15:21 UTC, yuval-hazaz reviewed
Well done! everything looks good.
Please remove the changes included in package-lock.josn

2021-07-19 19:36 UTC, yuval-hazaz requested changes

2021-07-19 19:36 UTC, yuval-hazaz commented on packages/amplication-data-service-generator/src/server/user-entity.ts
> +  unique: true,
this should not be unique

2021-07-20 04:59 UTC, lalit8347 commented on packages/amplication-data-service-generator/src/server/user-entity.ts
> +  unique: true,
Yes I will it change in next PR.

2021-07-20 07:10 UTC, yuval-hazaz approved these changes

2021-07-20 07:10 UTC, merged