Split setting page in 3 page, moving existing feild to new tab
amplication/amplication pull request #1700
Opened 2021-08-10 12:17 UTC by lalit8347

(amplication-client)  App setting is divided in to 3 tabs, Db setting , App Setting and Auth Setting.

2021-08-10 12:45 UTC, yuval-hazaz requested changes
Well done!
Please see my comments. 
If you want we can schedule a time to discuss

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationSettingsForm.tsx
> +function ApplicationSettingsForm({ match }: Props) {
rename to ApplicationDatabaseSettingsForms

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationForm.tsx
> +// import ApplicationSettingsForm from "./ApplicationSettingsForm";
remove comment

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationForm.tsx
> +          {/* <ApplicationSettingsForm applicationId={applicationId} /> */}
remove comment

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                    <TextField name="dbHost" autoComplete="off" label="Default Provider" value={ "Basic HTTP"}/>
This should be a dropdown with the available values

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                    <br />
remove <br/>

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                  name="dbName"
when connecting to the server, use the correct field

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                  name="dbPort"
when connecting to the server, use the correct field

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +const CLASS_NAME = "application-form";
rename to application-database-settings-form

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +import "./ApplicationForm.scss";
replace to ApplicationDatabaseSettingsForm.scss

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +              onSubmit={() => { }}
after connecting to the server add the missing initialValues and onSubmit

2021-08-10 12:45 UTC, yuval-hazaz commented on packages/amplication-client/src/models.ts
> +  { [SubKey in K]: Maybe<T[SubKey]> };
I am not sure where this changes originated from and why it was required to generate the files at all

2021-08-10 18:31 UTC, lalit8347 commented
require changes added.

2021-08-11 06:54 UTC, yuval-hazaz approved these changes
I approve this PR since all the required changes are part of the new form which anyway is not connected to the server yet.
In the next PR, when we add the connection to the server, please handle the new comments

2021-08-11 06:54 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                }>
use useCallback

2021-08-11 06:54 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                }
The logic should be a little different. 
Let's approve this PR and talk about the logic in the next PR when we connect the server

2021-08-11 06:54 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                  <div style={{marginTop :"10px"}}>
don't use inline style

2021-08-11 06:54 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationAuthSettingForm.tsx
> +                <div style={{marginTop :"10px"}}>
There is no need for the wrapper div.
the ToggleField should handle all the styling

2021-08-11 06:54 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationDatabaseSettingsForms.tsx
> +const CLASS_NAME = "ApplicationDatabaseSettingsForm.scss";
this should be kebab-case without the .scss

2021-08-11 08:17 UTC, merged