reserved names prevention on entity name or field
amplication/amplication pull request #2272
Opened 2022-02-05 16:15 UTC by noyjs

should fix #2269

2022-02-05 18:33 UTC, yuval-hazaz requested changes
well done
some minor requests for changes

2022-02-05 18:33 UTC, yuval-hazaz commented on packages/amplication-server/src/core/entity/entity.service.ts
> +          .trim()}" is a reserved name and cannot be used.`
Create a new Error and use a string template in the contractor to generate the message
see this example 
packages/amplication-server/src/core/app/ReservedEntityNameError.ts

2022-02-05 18:33 UTC, yuval-hazaz commented on packages/amplication-server/src/core/entity/entity.service.ts
> +export const CANNOT_USE_RESERVED_NAME_ERROR_MESSAGE = `"class" is a reserved name and cannot be used.`;
Remove this const

2022-02-05 18:33 UTC, yuval-hazaz commented on packages/amplication-server/src/core/entity/entity.service.ts
> +        );
same as above (use custom Error)

2022-02-05 18:33 UTC, yuval-hazaz commented on packages/amplication-server/src/core/entity/entity.service.ts
> +        `"${args.data?.name
same as above (use custom Error)

2022-02-05 18:33 UTC, yuval-hazaz commented on packages/amplication-server/src/core/entity/entity.service.ts
> +      throw new AmplicationError(
same as above (use custom Error)

2022-02-06 06:52 UTC, yuval-hazaz approved these changes

2022-02-06 06:52 UTC, yuval-hazaz commented
@mshidlov please also review this PR

2022-02-09 11:19 UTC, mshidlov commented
@noyjs thank you for submitting your PR, I finished doing some tests and this looks good. I'm going to merge this PR to release `0.11.3`

2022-02-09 11:19 UTC, merged