Update to Amplication README
amplication/amplication pull request #2314
Opened 2022-02-18 14:27 UTC by MoFoGo

Issue Number: N/A

## PR Details

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-02-18 14:27 UTC, MoFoGo commented
Updated the Amplication README

2022-02-18 16:33 UTC, yuval-hazaz requested changes
well done

2022-02-20 09:14 UTC, MoFoGo commented on README.md
> +### Setting up Amplication CLI [Amplication CLI](https://github.com/amplication/amplication/blob/master/packages/amplication-cli/README.md)
Removed CLI
Removed Data Service Generator

2022-02-20 09:18 UTC, MoFoGo commented on README.md
> +Amplication is using a mono-repo with multiple packages. To initialize all the packages on a local development environment, execute the following commands in the project root folder:
Updated.

2022-02-20 09:19 UTC, MoFoGo commented on README.md
> +### [Amplication Data Service Generator](https://github.com/amplication/amplication/tree/master/packages/amplication-data-service-generator)
Removed CLI and Data Service Generator.

2022-02-20 11:55 UTC, yuval-hazaz requested changes

2022-02-20 11:55 UTC, yuval-hazaz commented on README.md
> +You can use a manual step-by-step approach to set up Amplication in a local development environment. To do that, you should follow the following instructions for **Setting Up Amplication Server**, **
```suggestion
You can use a manual step-by-step approach to set up Amplication in a local development environment. To do that, you should follow the following instructions for **Setting Up Amplication Server**, and **Setting Up Amplication Client**.
```

2022-02-20 11:55 UTC, yuval-hazaz commented on README.md
> +### Setting up [Amplication Server](https://github.com/amplication/amplication/blob/master/packages/amplication-server/README.md)
```suggestion
#### Setting up [Amplication Server](https://github.com/amplication/amplication/blob/master/packages/amplication-server/README.md)
```

2022-02-20 11:55 UTC, yuval-hazaz commented on README.md
> +### Setting Up [Amplication Client](https://github.com/amplication/amplication/blob/master/packages/amplication-client/README.md)
```suggestion
#### Setting Up [Amplication Client](https://github.com/amplication/amplication/blob/master/packages/amplication-client/README.md)
```

2022-02-20 11:56 UTC, yuval-hazaz approved these changes

2022-02-20 11:56 UTC, merged

2022-02-20 19:35 UTC, yuval-hazaz commented
https://github.com/all-contributors please add @MoFoGo  for docs

2022-02-20 19:38 UTC, yuval-hazaz commented
@all-contributors please add @MoFoGo for docs