fix(client): Change colors
amplication/amplication pull request #2443
Opened 2022-03-16 15:29 UTC by RakeshPotnuru

Issue Number: #2431 

## PR Details

Changed background and hover colours for the support menu.

## PR Checklist
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-03-16 18:30 UTC, yuval-hazaz requested changes
Congrats on your first PR with Amplication.
Please see my suggestions 
Instead of using hardcoded color values, you should be using CSS variables

2022-03-16 18:30 UTC, yuval-hazaz commented on packages/amplication-client/src/Layout/SupportMenu.scss
> +  background-color: #373D57;
```suggestion
  background-color: var(--black10);
```

2022-03-16 18:30 UTC, yuval-hazaz commented on packages/amplication-client/src/Layout/SupportMenu.scss
> +      background-color: #444B66;
```suggestion
      background-color: var(--black20);
```

2022-03-17 09:26 UTC, yuval-hazaz approved these changes

2022-03-22 17:09 UTC, tupe12334 commented
Approved on staging

2022-03-22 21:31 UTC, merged