fix: change rgb color codes to css variables
amplication/amplication pull request #2455
Opened 2022-03-18 16:37 UTC by jainpawan21

Issue Number: #2451 

## PR Details

Changed hard coded RGB color codes to CSS variables

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-03-19 06:13 UTC, yuval-hazaz requested changes

2022-03-19 06:13 UTC, yuval-hazaz commented on packages/amplication-design-system/src/style/css-variables.scss
> +  --mui-toggle-track-background :#e3ddf6;
```suggestion
  --toggle-track-background :#e3ddf6;
```

2022-03-19 06:13 UTC, yuval-hazaz commented on packages/amplication-design-system/src/components/Toggle/Toggle.scss
> +        background: var(--mui-toggle-track-background);
```suggestion
        background: var(--toggle-track-background);
```

2022-03-19 06:26 UTC, yuval-hazaz commented
@jainpawan21 thanks for your contributions! it is very helpful and you are doing a great job
in order to make your contributions easier and to show our appreciation, I would be happy to add you to the @amplication/committers team. That will allow you to work on the main fork directly.

2022-03-19 08:37 UTC, jainpawan21 commented
> @jainpawan21 thanks for your contributions! it is very helpful and you are doing a great job in order to make your contributions easier and to show our appreciation, I would be happy to add you to the @amplication/committers team. That will allow you to work on the main fork directly.

Thank You @yuval-hazaz for your kind words.
I will be happy to be part of the **committers** team.

2022-03-20 10:44 UTC, yuval-hazaz approved these changes

2022-03-21 17:29 UTC, Harry-Hopkinson approved these changes

2022-03-22 17:05 UTC, tupe12334 approved these changes

2022-03-22 21:35 UTC, merged