fix(amplication-server): validate numbers min/max to ensure min is not greater than max, fixes #515
amplication/amplication pull request #2800
Opened 2022-05-25 03:34 UTC by MichaelSolati

Issue Number: #515

## PR Details

Validate that `minimumValue` is not greater than, or equal to, `maximumValue`.

## PR Checklist
- [ x] Tests for the changes have been added
- [ x] `npm test` doesn't throw any error

2022-05-25 05:46 UTC, yuval-hazaz commented
well done @MichaelSolati 👏

2022-05-25 05:50 UTC, yuval-hazaz requested changes
looks good to me
@MichaelSolati I think you should add a test to make it perfect

2022-05-25 10:17 UTC, tupe12334 commented on package-lock.json
> +      "name": "amplication",
Wich node and npm versions are you working with?

2022-05-25 10:19 UTC, tupe12334 commented
@MichaelSolati Pay attention to the branch name we usually use the issues number as this format 
<type>/<issus number>-<title>
fix/515-schema-validation

2022-05-25 18:09 UTC, MichaelSolati commented
> @MichaelSolati Pay attention to the branch name we usually use the issues number as this format /-<title> fix/515-schema-validation

Noted for next time

2022-05-31 10:53 UTC, tupe12334 commented on package-lock.json
> +      "name": "amplication",
@MichaelSolati ? I don't see why you added this property.

2022-06-06 17:25 UTC, yuval-hazaz commented
@MichaelSolati @tupe12334 what is the status of this PR?

2022-06-07 13:21 UTC, tupe12334 commented on package-lock.json
> +      "name": "amplication",
@MichaelSolati Can you please remove this change? or let me know if I can

2022-07-18 19:40 UTC, arielweinberger commented
Since there hasn't been a response in over a month, I am going to close this.

2022-07-18 19:40 UTC, closed without merging