fix: add support for new private repo in org
amplication/amplication pull request #2851
Opened 2022-05-31 20:18 UTC by jainpawan21

Issue Number: #2490 

## PR Details

Add support for create new private repo in org.

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-06-06 17:37 UTC, yuval-hazaz commented
@tupe12334 @alexbass86 please review

2022-06-07 13:55 UTC, tupe12334 commented on packages/amplication-server/.gitignore
> +.env
@jainpawan21 Why did you add the .env file here?

2022-06-12 05:22 UTC, jainpawan21 commented
@tupe12334, as mentioned in docs, I created a new file named .env.local and copied content of .env in it, then I tried to use GitHub services, but those were not working, 
Github services were only working with .env variables. 
That's why I thought of adding it in gitignore and created a new file `.env.example`

2022-06-19 11:53 UTC, yuval-hazaz commented
@tupe12334 please instruct @jainpawan21 how to proceed from here

2022-06-19 15:47 UTC, tupe12334 commented
@jainpawan21  Please remove from this pr all the stuff that is irrelevant to the issue like the .env stuff and the ci test for the git-service isn't passing

2022-06-25 20:18 UTC, tupe12334 approved these changes

2022-06-25 20:19 UTC, tupe12334 commented
@jainpawan21 I saw that you update the pr but you didn't update the git-service yet

2022-07-19 10:29 UTC, tupe12334 commented
> @yuval-hazaz What should we do with this one?

We need to fix the location of the button, I'm sure that @alexbass86 will not approve that

2022-07-24 08:34 UTC, yuval-hazaz commented
@tupe12334 can you please send a link or a screenshot?

2022-07-25 12:41 UTC, tupe12334 commented
This is in private mode
![Screen Shot 2022-07-25 at 15 40 49](https://user-images.githubusercontent.com/61761153/180779632-6f5af70a-50eb-4f9c-acfd-6edf205b01e2.png)

And this in public

![Screen Shot 2022-07-25 at 15 40 43](https://user-images.githubusercontent.com/61761153/180779640-5de7792b-f823-4ea9-9a10-8a9f14ef8e39.png)

@yuval-hazaz  and @alexbass86

2022-07-25 13:22 UTC, alexbass86 commented
> 
Hi, I designed a new popup for this feature. Please make sure it's aligned.

![a4](https://user-images.githubusercontent.com/96179897/180787480-f7cdf226-0c04-4ad6-af9c-f993d84a2617.png)

Figma:
https://www.figma.com/file/8Q9kB3b29FCh9ttVmOHm9u/Concept---Private-repo?node-id=1601%3A5670

2022-07-25 13:25 UTC, alexbass86 requested changes
I posted the design for this popup, and please make sure it's aligned

2022-07-28 09:34 UTC, yuval-hazaz commented
@alexbass86 thanks for the new design. 
I will approve this PR as it is and move forward
please open a new issue to use the new design.

@tupe12334 please merge this PR

2022-07-28 09:36 UTC, yuval-hazaz approved these changes

2022-07-28 09:58 UTC, alexbass86 commented
> @alexbass86 thanks for the new design. I will approve this PR as it is and move forward please open a new issue to use the new design.
> 
> @tupe12334 please merge this PR

done [new issue](https://github.com/amplication/amplication/issues/3250)

2022-08-01 08:35 UTC, tupe12334 commented
@jainpawan21 Do you want to work on the update or I will take it from here?

2022-08-01 14:00 UTC, jainpawan21 commented
> @jainpawan21 Do you want to work on the update or I will take it from here?

Hi @tupe12334, yes you can take it from there as there is new issue opened

2022-08-02 07:09 UTC, merged