fix: create temp folders for packages, fixes #2969
amplication/amplication pull request #2997
Opened 2022-06-29 01:16 UTC by MichaelSolati

Issue Number: #2969

## PR Details

Sets the environment variables for temporary folders to `.temp`. Also, git ignore them and add them to tsconfigs.

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-06-29 09:56 UTC, yuval-hazaz requested changes

2022-06-29 09:56 UTC, yuval-hazaz commented on ee/packages/amplication-git-pull-service/.env
> +STORAGE_PATH=.temp
based on @arielweinberger suggestion - it should be .amplication_temp 
please see this comment on the original issue 
https://github.com/amplication/amplication/issues/2969#issuecomment-1166203987

2022-07-10 14:47 UTC, yuval-hazaz commented
@tupe12334 I remember you said something about how the service is implemented and that changing the name will not work. 
Please add your comments here

@MichaelSolati @arielweinberger following Ofek's comments - please decide how to proceed with this one

2022-07-14 19:29 UTC, MichaelSolati commented
Sorry for the delay; it's ready for review again. @yuval-hazaz @arielweinberger @tupe12334

2022-07-16 06:57 UTC, yuval-hazaz commented
Thanks @MichaelSolati 
I had a talk with @tupe12334 a couple of days ago, and he mentioned that the current implementation of the path is absolut and not relative to the working directory, so I think it will take some more effort to make it work as expected.

@tupe12334 can you please and if true, please let us know how we should proceed from here

2022-07-17 08:05 UTC, tupe12334 commented
> I had a talk with @tupe12334 a couple of days ago, and he mentioned that the current implementation of the path is absolut and not relative to the working directory, so I think it will take some more effort to make it work as expected.
> 
> @tupe12334 can you please and if true, please let us know how we should proceed from here

The code in ```packages/amplication-server/src/core/build/utils/BuildFilesSaver/BuildFilesSaver.ts``` is saving the files in an absolute path, to save is as a relative path we can change the logic in the saving class but we need to update the logic in the loader side in the ```packages/amplication-git-pull-request-service/src/core/diff/utils/BuildPathFactory.ts``` file

2022-07-17 13:33 UTC, yuval-hazaz commented
> The code in `packages/amplication-server/src/core/build/utils/BuildFilesSaver/BuildFilesSaver.ts` is saving the files in an absolute path, to save is as a relative path we can change the logic in the saving class but we need to update the logic in the loader side in the `packages/amplication-git-pull-request-service/src/core/diff/utils/BuildPathFactory.ts` file

Moving to relative paths may impact the prod env - so we need to carefully think about it before moving in this direction.
I would love to understand the impact of the current implementation on new contributors in the onboarding process. how clear is it for new developers to setup a local dev env to work with Amplication?

@arielweinberger @tupe12334 @abrl91 @mshidlov

2022-07-25 13:56 UTC, arielweinberger commented
After discussing with @tupe12334 here is a good solution:

We'll write to a local `.amplication/builds` folder (at the Amplication root folder). This will enrich the experience as we don't write files to their filesystem root.

We will need to make sure we mount the EFS volume to the `.amplication/builds` folder. This way we don't affect how Production works.

@MichaelSolati Should we cake over from here, or are you interested in doing it?

It's important to make sure we update the helm configuration and docker-compose as well.

2022-07-25 14:57 UTC, MichaelSolati commented
@tupe12334 and @arielweinberger, I don't want to be the one holding this back, if y'all have time to polish this up to land it, then please go for it. If not I'll have the time in the latter half of this week to work on it. Either way, let me know.

2022-07-28 12:00 UTC, tupe12334 commented
We need @MoFoGo to doc this change

2022-07-28 12:57 UTC, tupe12334 commented
I update this pr to meet our spec, from now on there will be a default .amplication folder that all the builds will auto save to `.amplicaiton/builds`

2022-07-28 13:56 UTC, arielweinberger commented
Really awesome @tupe12334 well done both @MichaelSolati

2022-07-28 13:56 UTC, arielweinberger approved these changes

2022-07-28 14:13 UTC, yuval-hazaz commented on packages/amplication-git-pull-request-service/README.md
> +| BASE_BUILDS_FOLDER | path to a folder where your builds will be saved | The default path will be inside your amplication repository
```suggestion
| BASE_BUILDS_FOLDER | absolute path to a folder where your builds will be saved | for development purposes, leave this variable empty to use `.amplication/storage` relative to the execution folder. 
```

2022-07-28 14:13 UTC, yuval-hazaz commented on packages/amplication-server/README.md
> +| BASE_BUILDS_FOLDER | path to a folder where your builds will be saved | The default path will be inside your amplication repository |
see comment above

2022-07-28 14:14 UTC, yuval-hazaz commented on packages/amplication-storage-gateway/README.md
> +| BASE_BUILDS_FOLDER | path to a folder where your builds will be saved | The default path will be inside your amplication repository |
see comment above

2022-07-28 14:14 UTC, yuval-hazaz commented on packages/amplication-storage-gateway/src/constants.ts
> +export const DEFAULT_BUILDS_FOLDER = join(DOT_AMPLICATION_FOLDER, "builds");
add path to storage

2022-07-28 14:15 UTC, yuval-hazaz commented on ee/packages/amplication-git-pull-service/README.md
> +| STORAGE_PATH | max storage snapshot | The default path will be inside your amplication repository |
see other comment about the description

2022-07-28 14:15 UTC, yuval-hazaz commented on .amplication/.gitignore
> +github/
storage/

2022-07-28 15:55 UTC, merged

2022-07-31 07:29 UTC, yuval-hazaz commented
@MoFoGo we should document this. We can prepare a doc about the build process.
please add do your backlog and let's discuss this once you are ready