3014 client page title
amplication/amplication pull request #3015
Opened 2022-07-03 12:45 UTC by barshimi

Issue Number: N/A

## PR Details

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-07-03 13:11 UTC, arielweinberger commented
@barshimi Please make sure you specify an issue title, a description and link it to a milestone?

2022-07-03 14:56 UTC, yuval-hazaz requested changes

2022-07-03 14:56 UTC, yuval-hazaz commented on packages/amplication-client/src/Layout/PageContent.tsx
> +      <title>{pageTitle || "Amplication"}</title>
```suggestion
      <title>Amplication{ pageTitle ? ` |  ${pageTitle}`:""  }</title>
```

2022-07-04 06:22 UTC, yuval-hazaz requested changes

2022-07-04 06:22 UTC, yuval-hazaz commented on packages/amplication-client/src/Layout/PageContent.tsx
> +        <title>{`Amplication${pageTitle ? `-${pageTitle}` : ""}`}</title>
```suggestion
        <title>{`Amplication${pageTitle ? ` | ${pageTitle}` : ""}`}</title>
```

2022-07-04 06:22 UTC, yuval-hazaz commented on packages/amplication-client/src/Layout/PageContent.tsx
> +        <title>{`Amplication${pageTitle ? `-${pageTitle}` : ""}`}</title>
instead of dash, I prefer using a pipe with spaces before and after

2022-07-04 06:23 UTC, yuval-hazaz approved these changes

2022-07-04 11:51 UTC, merged