Feat/3016 generated app =>  update readme files for the server and the admin-ui
amplication/amplication pull request #3017
Opened 2022-07-03 13:31 UTC by morhag90

Issue Number: #3016 

## PR Details

After the split of the docker files we needed to update readme files for the server and the admin-ui with new commands and add the env variables list 

## PR Checklist
- [ X] Tests for the changes have been added
- [ X] `npm test` doesn't throw any error

2022-07-03 13:51 UTC, mshidlov commented on packages/amplication-data-service-generator/src/server/static/README.md
> +
```suggestion
```
```

2022-07-03 13:53 UTC, mshidlov commented on packages/amplication-data-service-generator/src/server/static/README.md
> +
![image](https://user-images.githubusercontent.com/91742238/177042918-b8b33925-6dde-40ee-9f2a-b032a53a646d.png)

2022-07-03 14:01 UTC, mshidlov commented on packages/amplication-data-service-generator/src/server/static/package.json
> +    "docker:down": "docker-compose down --volumes"
```suggestion
    "compose:up": "docker-compose up -d",
    "compose:down": "docker-compose down --volumes"
```

2022-07-03 14:02 UTC, mshidlov commented
@morhag90 I'm missing the Admin UI readme

2022-07-03 14:02 UTC, mshidlov requested changes
please see my comments

2022-07-03 14:02 UTC, morhag90 commented on packages/amplication-data-service-generator/src/server/static/README.md
> +
done

2022-07-04 08:47 UTC, mshidlov requested changes

2022-07-04 10:12 UTC, morhag90 commented on packages/amplication-data-service-generator/src/server/static/README.md
> +- Or, instead running db only, run docker with server
@mshidlov something like that?:
![image](https://user-images.githubusercontent.com/97830649/177133922-ffad9b97-d6b3-4cdd-9c6e-a67e980b41b9.png)

2022-07-04 10:45 UTC, mshidlov commented on packages/amplication-data-service-generator/src/server/static/README.md
> +- Or, instead running db only, run docker with server
@morhag90 
Set up development environment 
db:init
npm start

Run server deployment (docker-compose)

2022-07-04 12:37 UTC, merged

2022-07-04 13:44 UTC, yuval-hazaz reviewed
@morhag90 please see my comments

2022-07-04 13:44 UTC, yuval-hazaz commented on packages/amplication-data-service-generator/src/admin/static/README.md
> +In the `admin-ui` subdirectory, you can run:
This should be 3001

2022-07-04 13:44 UTC, yuval-hazaz commented on packages/amplication-data-service-generator/src/server/static/README.md
> +| JWT_SECRET_KEY       | JWT secret                               | XAFzBpM3es                                                  |
I dont think we should use a real password - it should be clear to the user that this is an example they need to change - so using something like 123456 or changMe is better