add infra-chart
amplication/amplication pull request #3042
Opened 2022-07-07 09:03 UTC by shaharblanksela

2022-07-07 13:46 UTC, arielweinberger approved these changes
Looks great! I'd wait for a review from @mshidlov since I am lacking some context.

2022-07-10 18:08 UTC, mshidlov requested changes

2022-07-10 18:08 UTC, mshidlov commented on helm/charts/services/amplication-server/values.yaml
>  postgresql:
This should be taken from the infra chart

2022-07-13 08:20 UTC, shaharblanksela commented on helm/charts/amplication/values-amit.yaml
> +  pv:
Yes, they are. PV is a resource outside the namespace which connects the PVC request from volume data to be stored in efs.  volume is the name of the folder located in the pod.

2022-07-13 08:24 UTC, shaharblanksela commented on helm/charts/amplication/values-common.yaml
> +      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.1
Changed. I pulled the folder of the helm chart from my previous branch and this is a value from it.  not relevant changed it to '0'.

2022-07-13 08:25 UTC, shaharblanksela commented on helm/charts/amplication/values-common.yaml
> +      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.1
Changed. I pulled the folder of the helm chart from my previous branch and this is a value from it. not relevant changed it to '0'.

2022-07-13 08:31 UTC, shaharblanksela commented on helm/charts/amplication/values-mor.yaml
> +      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/mor-app/installations/new?state={state}"
I saw that values-mor is not updated with the rest of the custom-values (like Shimi & Amit) if it doesn't relevant for now I'll restore the values-mor from 'master'.

2022-07-13 08:32 UTC, shaharblanksela commented on helm/charts/amplication/values-mor.yaml
>      enabled: true
Done

2022-07-13 08:32 UTC, shaharblanksela commented on helm/charts/amplication/values-prod.yaml
> -      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
restored.

2022-07-13 08:34 UTC, shaharblanksela commented on helm/charts/amplication/values-staging-os.yaml
> -      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
It's already in values-common and it doesn't change through environments.

2022-07-13 08:40 UTC, shaharblanksela commented on helm/charts/services/amplication-git-pull-request-service/values.yaml
> +  enabled: false
Done

2022-07-13 08:42 UTC, shaharblanksela commented on helm/charts/services/amplication-git-pull-service/Chart.yaml
>    condition: postgres.install
No, it's the bug that we can't put nested charts inside another chart as I mentioned above.

2022-07-13 08:45 UTC, shaharblanksela commented on helm/charts/services/amplication-git-pull-service/values.yaml
>    enabled: false
Done

2022-07-13 14:23 UTC, merged