Feat/3108 ci update how we include docker images to support generators not part of our helm charts
amplication/amplication pull request #3389
Opened 2022-08-08 06:44 UTC by mshidlov

Issue Number: #3108

## PR Details

### Update amplication CI workflow:
1. packages to build: all packages that have a Dockerfile will be included in the image building process
2. Simplify git changes job: get all folders that have changes, against the main (master) branch on a push and against the base branch on a PR.

### Added new GitHub Actions:
1. find-folders-by - will return all folders that contain a searched file. used by the CI workflow to retrieve all folders that contain Dockerfile.
2. get-package-names - returns corresponding package names for a given list of folders. The action is to search for the package name from the package.json files. used in the CI workflow to retrieve the package names to folders that has a git diff.

### Update get-services-hash GitHub Action
Improve the hashing process and add folders to hash input instead of calculate the folders from the charts.

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-08-08 07:14 UTC, arielweinberger commented
Let's arrange a pair review on this over a call, so I can become more familiar with it please 😄

2022-08-09 08:02 UTC, arielweinberger requested changes

2022-08-09 08:02 UTC, arielweinberger commented
Let's remove comments overhead :)

2022-08-11 09:07 UTC, mshidlov commented on packages/amplication-data-service-generator/Dockerfile
> +# RUN cd admin; npm ci --silent;
That file will be updated in the DSG separation - the comment is only to make it run without failing I don't want to touch that file

2022-08-11 09:26 UTC, arielweinberger approved these changes

2022-08-11 09:27 UTC, arielweinberger commented
Cool! Approved. It would be great to have a 30-minutes session with the team, syncing them with this change so they understand (more or less) what's new.

2022-10-26 15:07 UTC, closed without merging