better grammar
amplication/amplication pull request #3484
Opened 2022-08-17 08:30 UTC by juno-w

Issue Number: N/A

## PR Details
Better text
```
API tokens are used to authenticate requests to the Amplication API. They are specifically required for Amplication CLI.
Tokens are valid for 30 days following creation or last use. The 30 day expiration period automatically refreshes with each API.
```

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

2022-08-17 08:34 UTC, arielweinberger requested changes

2022-08-17 08:34 UTC, arielweinberger commented on packages/amplication-client/src/Settings/ApiTokenList.tsx
> +        API tokens are used to authenticate requests to the Amplication API. They are specifically required for Amplication CLI.
```suggestion
        API tokens are used by the Amplication CLI to make requests to the API.
```
I think in this case, less is more.

2022-08-17 10:27 UTC, arielweinberger approved these changes

2022-08-17 15:43 UTC, yuval-hazaz commented
Thank you for your first contribution with Amplication 🚀

2022-08-17 15:44 UTC, merged

2022-09-01 11:08 UTC, souravjain540 commented
your name and email @juno-w ?

2022-09-01 13:01 UTC, juno-w commented
> your name and email @juno-w ?

Dm'ed your Twitter :)