fix/Add descriptive text to the General Settings page #3445
amplication/amplication pull request #3507
Opened 2022-08-18 10:48 UTC by pinkelephant4

Issue Number: N/A

## PR Details

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-08-18 13:51 UTC, yuval-hazaz requested changes

2022-08-18 13:51 UTC, yuval-hazaz commented on packages/amplication-client/src/Application/ApplicationForm.tsx
> +                    <h5>Enter a name and description for your app, and choose your app color.</h5>
```suggestion
                    <h5>Enter a name and description for your app, and select a color.</h5>
```

2022-08-18 13:51 UTC, yuval-hazaz commented
Thanks for your first contribution to Amplication

2022-08-18 13:52 UTC, yuval-hazaz approved these changes

2022-08-19 19:31 UTC, merged

2022-09-01 11:08 UTC, souravjain540 commented
your name and email @pinkelephant4 ?

2022-09-02 15:41 UTC, pinkelephant4 commented
> your name and email @pinkelephant4 ?

Ananya Maheshwari
maheshwari.ananya99@gmail.com