Update CommandPalette.tsx
amplication/amplication pull request #3678
Opened 2022-09-01 07:30 UTC by Himanxu1

remove the @ts-ignore comments

Issue Number: #3658 

## PR Details

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-09-01 07:44 UTC, souravjain540 commented
@arielweinberger please approve

2022-09-01 07:44 UTC, souravjain540 commented
@tupe12334 approve this

2022-09-01 07:49 UTC, tupe12334 commented on packages/amplication-client/src/CommandPalette/CommandPalette.tsx
> +import ReactCommandPalette from "@types/react-command-palette";
Why did you change the import to @types/react-command-palette?

2022-09-01 07:50 UTC, tupe12334 commented
Why didn't you add the @types/react-command-palette lib to the dev dependencies?

2022-09-01 13:06 UTC, tupe12334 commented
> @types/react-command-palette

Add it to the dev dependencies not the code

2022-09-01 18:38 UTC, arielweinberger commented
So I see the package is already in the dev dependencies ([see here](https://github.com/Himanxu1/amplication/blob/patch-7/packages/amplication-client/package.json#L27))

2022-09-02 12:03 UTC, arielweinberger requested changes
The correct way to fix this is to install:

```
npm install -D @types/react-command-palette
```

into Amplication Client, and then remove the @ts-ignore line. Will you please try that @Himanxu1 and make sure the client project compiles fine with no TS complaints?

2022-09-08 05:29 UTC, yuval-hazaz commented
@arielweinberger what do we need to move forward with this PR?

2022-09-12 17:31 UTC, AllMikeNoIke commented
Hi @arielweinberger, I have made pull request #3791 to also address issue #3658. I know @Himanxu1 was originally assigned to this issue, so if this goes against community guidelines, I will close the PR.

2022-09-12 18:13 UTC, closed without merging