3762 validate topic name
amplication/amplication pull request #3838
Opened 2022-09-15 15:49 UTC by EugeneTseitlin

Closes: #3762 

## PR Details

Added validation for topic name

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-09-15 19:24 UTC, arielweinberger requested changes

2022-09-15 19:24 UTC, arielweinberger commented on packages/amplication-client/src/Components/TopicNameField.tsx
> +  // @ts-ignore
Please remove `// @ts-ignore`. Fix the root cause if there are any issues.

2022-09-16 08:48 UTC, yuval-hazaz approved these changes

2022-09-16 09:04 UTC, arielweinberger approved these changes

2022-09-16 10:10 UTC, merged