Throw an error when MySQL plugin is installed and one of the entities' fields types is MultiSelectOptionSet
amplication/amplication pull request #3844
Opened 2022-09-16 18:11 UTC by abrl91

Issue Number: N/A

## PR Details

Throw an error when MySQL plugin is installed and one of the entities' fields types is MultiSelectOptionSet

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

2022-09-16 18:14 UTC, abrl91 commented
@MoFoGo I assigned you as a reviewer because I need your input about the error message

2022-09-17 06:27 UTC, yuval-hazaz requested changes

2022-09-17 06:27 UTC, yuval-hazaz commented on packages/amplication-data-service-generator/src/create-data-service-impl.ts
>    const entityIdToEntity: Record<string, Entity> = {};
this validation should be part of the plugin and not part of DSG
The plugin should handle one of the main events (e.g. beforeCreateServer) and if needed the plugin will:
1. write the error message to the logger 
2. throw and error? or "skip" the entire process

2022-09-17 10:25 UTC, abrl91 commented
Will be handled on the plugin

2022-09-17 10:25 UTC, closed without merging