fix: styles for issues 3891 & 3895
amplication/amplication pull request #3920
Opened 2022-09-19 19:48 UTC by b4s36t4

Issue Number: #3891 #3895 

## PR Details

This solves the issues mentioned above with stylings and changed text as per #3895 

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-10-03 07:16 UTC, yuval-hazaz requested changes
please split the pull request, one for each issue. you can close this one and send two new PRs if that is easier

2022-10-03 07:16 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ProjectList.scss
> +}
the styles should be inherited from the design-system instead of settings specific style on the button here

2022-10-03 07:16 UTC, yuval-hazaz commented on packages/amplication-client/src/VersionControl/BuildPage.scss
> +      height: 500px;
The height should not be fixed and should be used relatively to the page content. we can consider a parent with 100% and then flex 1 to use the entire space left by the siblings 

let me know if you need more details on instructions on this one

2022-10-08 07:02 UTC, yuval-hazaz commented
@b4s36t4 please let us know if you need any help moving forward with this PR

2022-10-08 07:04 UTC, b4s36t4 commented
I'll update the PRs.

2022-10-08 07:07 UTC, b4s36t4 commented
I'll update the PRs.

2022-10-18 10:25 UTC, souravjain540 commented
> I'll update the PRs. 

Any updates?

2022-11-28 07:13 UTC, yuval-hazaz commented
closing this PR for inactivity. 
@b4s36t4 please feel free to pick up an issue that is available for the community when you are ready

2022-11-28 07:13 UTC, closed without merging