Fix open pull request on GitHub button
amplication/amplication pull request #3950
Opened 2022-09-24 09:26 UTC by abrl91

Issue Number: #3811 

## PR Details
- when the user is in the context of a service (resource), the open with GitHub button opens the last pull request (last build)
- in a context of  project, the open with GitHub button opens the repository URL that is connected to the **project**.

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

2022-09-24 09:31 UTC, abrl91 commented
"in a context of project, the open with GitHub button opens the repository URL that is connected to the project"

@GreenMachine01 @yuval-hazaz 
This is the decision I have made, but we may think about it.
A project can have more than one resource. Each resource can be connected to a different git repository. 
When the user clicks on the build button, it creates a commit with x number of builds, a build to every resource on the project. 
We can decide that the button opens the last build no matter what, but then it can cause strange behavior. For example, the user is on one of his services pages, and clicks on the open with GitHub button, but the current service is not the one that was built last, and as a result, the wrong pull request will be opened

2022-09-25 06:10 UTC, yuval-hazaz requested changes

2022-09-25 06:10 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx
> +            )}
use only one <a> and make sure that value returned from githubUrl is equal to githubUrl when needed

2022-09-25 06:10 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx
> +      return null;
```suggestion
      return gitRepositoryUrl;
```

2022-09-25 06:10 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx
> +    return log?.meta?.githubUrl || null;
```suggestion
    return log?.meta?.githubUrl || gitRepositoryUrl;
```

2022-09-25 08:57 UTC, yuval-hazaz approved these changes

2022-09-25 08:57 UTC, merged