use amplification nest logger module in amplification-git-service
amplication/amplication pull request #4055
Opened 2022-10-04 21:37 UTC by ahlavorato

Issue Number: [#3396](https://github.com/amplication/amplication/issues/3396)

## PR Details

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-10-05 16:38 UTC, arielweinberger approved these changes

2022-10-08 06:57 UTC, yuval-hazaz commented
@ahlavorato please execute 'npm run format' and push the changes to fix the errors

2022-10-08 06:57 UTC, yuval-hazaz requested changes
please fix formatting error

2022-10-08 07:09 UTC, yuval-hazaz commented
run branch

2022-10-09 09:43 UTC, yuval-hazaz approved these changes

2022-10-11 12:58 UTC, merged