Update package.json
amplication/amplication pull request #4168
Opened 2022-10-16 12:33 UTC by astitva0011

Close #[issue-number]

## PR Details

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-10-17 03:07 UTC, tupe12334 requested changes
Please update package-lock file as well

2022-10-17 09:43 UTC, astitva0011 reviewed
requested change

2022-10-18 07:50 UTC, abrl91 commented
@astitva0011 I can't see a change in `package-lock.json`

2022-10-18 08:00 UTC, abrl91 commented
@astitva0011 I saw you opened a new PR for that. Can you please close the following PR https://github.com/amplication/amplication/pull/4180 and make the change on this PR

2022-10-18 08:54 UTC, astitva0011 commented
> @astitva0011 I saw you opened a new PR for that. Can you please close the following PR #4180 and make the change oni ha

> @astitva0011 I saw you opened a new PR for that. Can you please close the following PR #4180 and make the change on this PR

i have closed the pr

2022-10-18 09:03 UTC, abrl91 commented
> > @astitva0011 I saw you opened a new PR for that. Can you please close the following PR #4180 and make the change oni ha
> 
> > @astitva0011 I saw you opened a new PR for that. Can you please close the following PR #4180 and make the change on this PR
> 
> i have closed the pr

Thank you, now you just need to apply the change to the package-lock.json here, on this PR

2022-10-18 09:40 UTC, abrl91 commented on package.json
> -  "dependencies": {
Why did you remove all the dependencies section?

2022-10-18 09:43 UTC, abrl91 commented
@astitva0011  on this commit you have the right solution. Just run `npm install` in the root Amplication folder to update the `package-lock.json`

2022-10-18 10:44 UTC, closed without merging