Social Media Advocacy
amplication/amplication pull request #4181
Opened 2022-10-17 20:04 UTC by Gokul-Ks

Close #4031 

## PR Details

Added Social Post links

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-10-18 05:42 UTC, souravjain540 requested changes
As the issue mentions, we said that it should be some content that gives value to the audience, you can explain any feature or the github contribution process.

and it was supposed to be a thread.


please make the changes and i will approve, also tag us

2022-10-19 08:54 UTC, Riyazmd786 commented
Great

2022-10-22 10:29 UTC, Gokul-Ks commented
@souravjain540 I have completed the requested changes

2022-10-22 19:13 UTC, souravjain540 approved these changes

2022-10-26 07:17 UTC, merged