Feat/4044 delete topic
amplication/amplication pull request #4353
Opened 2022-11-13 08:28 UTC by morhag90

Close #4018 

## PR Details

Add delete topic in message broker resource 

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

2022-11-13 10:40 UTC, arielweinberger commented
Let's wait with merging this until we test the new Nx React setup, just to minimize chances errors introduced.

2022-11-20 11:10 UTC, yuval-hazaz requested changes
in addition to the below - we need to throw exceptions in the settings blocks so they will not be deletable

2022-11-20 11:10 UTC, yuval-hazaz commented on src/schema.graphql
> +}
remove this file

2022-11-20 11:10 UTC, yuval-hazaz commented on packages/amplication-server/src/core/topic/topic.service.ts
> +    protected readonly serviceTopics: ServiceTopicsService
```suggestion
    protected readonly serviceTopicsService: ServiceTopicsService
```

2022-11-20 11:10 UTC, yuval-hazaz commented on packages/amplication-server/src/core/topic/topic.module.ts
> +  exports: [TopicService, TopicResolver, ServiceTopicsService],
```suggestion
  exports: [TopicService, TopicResolver],
```

2022-11-20 11:10 UTC, yuval-hazaz commented on packages/amplication-server/src/core/topic/topic.module.ts
> +  providers: [TopicService, TopicResolver, ServiceTopicsService],
```suggestion
  providers: [TopicService, TopicResolver],
```

2022-11-21 08:42 UTC, morhag90 commented on packages/amplication-server/src/core/topic/topic.module.ts
> +  exports: [TopicService, TopicResolver, ServiceTopicsService],
removed

2022-11-21 14:19 UTC, morhag90 commented on packages/amplication-client/src/Topics/Topic.tsx
> +  const { topicId, resource } = match?.params ?? {};
history

2022-11-21 15:59 UTC, yuval-hazaz approved these changes

2022-11-21 17:22 UTC, merged