chore: add health check on postgresql
amplication/amplication pull request #4364
Opened 2022-11-14 11:41 UTC by overbit

Close: #4430

## PR Details

Add health check on postgresql container for local development environment.

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-11-21 09:07 UTC, EugeneTseitlin approved these changes

2022-11-21 09:07 UTC, EugeneTseitlin approved these changes

2022-11-21 09:10 UTC, EugeneTseitlin requested changes
Please, assign this PR to the issue. The code change is fine.

2022-11-23 13:36 UTC, overbit commented
Added issue related to this change

2022-11-28 07:26 UTC, yuval-hazaz commented
@overbit can we merge this PR?

2022-11-28 09:07 UTC, EugeneTseitlin approved these changes

2022-11-28 09:07 UTC, merged