Feat/poc mongodb plugin
amplication/amplication pull request #4509
Opened 2022-12-01 09:32 UTC by morhag90

Close: #1959 

## PR Details

Add support to mongoDB prisma creation. 
## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

2022-12-01 16:33 UTC, overbit requested changes

2022-12-01 16:33 UTC, overbit commented on helm/charts/dsg-runner-infra/templates/sensor.yaml
> +                        image: "407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-data-service-generator:feat/poc-mongodb-plugin"
It needs update before we can merge it.

2022-12-01 16:33 UTC, overbit commented on ee/packages/amplication-git-pull-service/scripts/clean.ts
> +  }> = await prisma.$queryRaw`SELECT tablename from pg_tables where schemaname = 'public';`;
Undo this in order to fix the ci pipeline. 
Locally you'd need to remove your node_modules and run `npm i`

2022-12-01 16:33 UTC, overbit commented on packages/amplication-data-service-generator/src/server/static/scripts/clean.ts
> +  }> = await prisma.$queryRaw`SELECT tablename from pg_tables where schemaname = 'public';`;
Undo this in order to fix the ci pipeline.
Locally you'd need to remove your node_modules and run npm i

2022-12-01 16:33 UTC, overbit commented on packages/amplication-prisma-db/prisma/clean.ts
> +  }> = await prisma.$queryRaw`SELECT tablename from pg_tables where schemaname = 'public';`;
Undo this in order to fix the ci pipeline.
Locally you'd need to remove your node_modules and run npm i

2022-12-02 08:14 UTC, abrl91 commented on packages/amplication-data-service-generator/package.json
> +    "@amplication/code-gen-types": "^1.1.7",
This one shouldn't be here

2022-12-02 08:17 UTC, abrl91 commented on helm/charts/dsg-runner-infra/templates/sensor.yaml
> +                        image: "407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-data-service-generator:feat/poc-mongodb-plugin"
I think this one is for development purposes and should be reverted. Make sure when you merge this PR this value represents the last image sha of the dsg

2022-12-07 18:04 UTC, yuval-hazaz approved these changes

2022-12-07 18:24 UTC, yuval-hazaz approved these changes

2022-12-07 18:25 UTC, merged