change our implementation of working with multiple Prisma clients
amplication/amplication pull request #4544
Opened 2022-12-05 17:12 UTC by abrl91

Close: #4513

## PR Details

- change the output of prisma client on:
  - amplication/prisma-db
  - amplication/git-pull-service

from:
`node_modules/@amplication/prisma-clients/amplication-prisma-db`
`node_modules/@amplication/prisma-clients/amplication-git-pull-service`

to:
`src/generated-prisma-client`

- Implement the changes needed to `amplication/server` and `amplication/git-push-webhook` after this refactor on:

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

2022-12-07 15:55 UTC, overbit requested changes

2022-12-07 15:55 UTC, overbit commented on packages/amplication-server/Dockerfile
> +COPY ./packages/amplication-prisma-db/src/generated-prisma-client ./packages/amplication-prisma-db/src/generated-prisma-client
This part should be redundant. Let's remove it.
```suggestion
```

2022-12-11 09:08 UTC, barshimi approved these changes

2022-12-11 09:09 UTC, barshimi approved these changes

2022-12-11 13:01 UTC, merged