Dynamic install of plugins
amplication/amplication pull request #4576
Opened 2022-12-07 12:17 UTC by tupe12334

This PR adds the logic of dynamically installation of plugins in the generate-code DSG executer

2022-12-11 15:00 UTC, barshimi commented on packages/amplication-data-service-generator/src/generate-code.ts
> +    const modules = await (
why don't you import the file before the run and use it on invoke ?

2022-12-11 15:00 UTC, barshimi commented on packages/amplication-data-service-generator/src/tests/pluginInstallation.ts
> +import { plugins } from "../../scripts/constants/example-plugins";
again

2022-12-12 08:49 UTC, overbit requested changes

2022-12-12 08:49 UTC, overbit commented on packages/amplication-data-service-generator/src/dynamic-plugin-installation.ts
> +  );
This approach might bring us easily into a dependency hell https://npm.github.io/how-npm-works-docs/theory-and-design/dependency-hell.html.

Plus is locking our solution to only support NPM leaving most used package managers like yarn and pnpm out to support. 
Possibly, a stronger solution would be to bundle all the dependencies of a plugin within the plugin itself.

2022-12-12 09:21 UTC, overbit commented on packages/amplication-data-service-generator/src/dynamic-plugin-installation.ts
> +  );
Plus we might have network issues (that are always a possibility) that will affect the installation of npm packages in runtime and, consequently, the code generation.

2022-12-18 09:06 UTC, GreenMachine01 commented
@tupe12334 Please see feedback and resolve conflicts.

2022-12-20 10:40 UTC, merged