Fix "Cannot find models" Prisma bug
amplication/amplication pull request #4705
Opened 2022-12-20 13:14 UTC by arielweinberger

Close: #4704

## PR Details

After some research, it seems that the bug (mentioned in the ticket) was caused by messing with the Prisma import paths.

This PR makes it so that upon running `npx nx prisma:generate`, each service will get its own relative Prisma client and eliminate the need to import the Prisma client from a sibling folder.

It has been tested and it works properly.

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-12-20 13:44 UTC, abrl91 requested changes

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/auth/auth.service.spec.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { PrismaService, Account, Workspace, User, UserRole, Project } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/block/block.service.spec.ts
> +import { Prisma, EnumResourceType } from "../../prisma";
```suggestion
import { PrismaService, Prisma, EnumResourceType } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/entity/entity.resolver.spec.ts
> +import type {
are you sure we need the "type", because I saw in other places that we don't need it

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/entity/entity.service.spec.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { PrismaService, Prisma, EnumEntityAction } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/entity/entity.service.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { Prisma, PrismaService } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/git/__tests__/git.service.spec.ts
> +import { PrismaService } from "../../../prisma";
```suggestion
import { PrismaService, EnumResourceType } from "../../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/git/git.provider.service.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { PrismaService, Prisma, EnumResourceType } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/project/project.service.ts
> +import { EnumResourceType } from "../../prisma";
```suggestion
import { PrismaService, EnumResourceType } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/resource/resource.resolver.spec.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { PrismaService, EnumResourceType } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/resource/resource.service.spec.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { PrismaService, EnumResourceType, GitRepository, Prisma } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/resource/resource.service.ts
> +import { EnumResourceType, GitRepository, Prisma } from "../../prisma";
```suggestion
import { PrismaService, EnumResourceType, GitRepository, Prisma } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/subscription/paddle.service.spec.ts
> +import type {
do we need the "type"?

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/user/user.service.spec.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { Prisma, PrismaService } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/user/user.service.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { Prisma, PrismaService } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-server/src/core/workspace/workspace.service.ts
> +import { PrismaService } from "../../prisma";
```suggestion
import { Prisma, PrismaService } from "../../prisma";
```

2022-12-20 13:44 UTC, abrl91 commented on packages/amplication-prisma-db/src/index.ts
> +// export * from "./prisma.service";
can we delete this file?

2022-12-21 08:23 UTC, yuval-hazaz commented on packages/amplication-data-service-generator/src/server/static/scripts/clean.ts
> +  }> = await prisma.$queryRaw`SELECT tablename from pg_tables where schemaname = 'public';`;
Why do we keep getting these changes? is that something we are already working to resolve?

2022-12-21 10:12 UTC, arielweinberger commented on packages/amplication-data-service-generator/src/server/static/scripts/clean.ts
> +  }> = await prisma.$queryRaw`SELECT tablename from pg_tables where schemaname = 'public';`;
I'm not sure. I think it's caused by the pre-commit hook for the formatter, which for some reason works differently on individual's machines.

2022-12-21 10:26 UTC, arielweinberger commented on ee/packages/amplication-git-push-webhook-service/src/prisma/prisma.module.ts
> +@Module({
Fixed

2022-12-21 12:46 UTC, abrl91 approved these changes

2022-12-21 13:06 UTC, merged