change the plugins catalog resource
amplication/amplication pull request #4755
Opened 2022-12-28 16:26 UTC by barshimi

Close: #4004 

## PR Details

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2022-12-28 19:23 UTC, barshimi commented
few notes regard this PR:

- I merged the changes of plugin API service into this branch in order to see full cycle of the process.
- I didn't finished design the css of the dropDown component. we need to refactor the select component to be more flexible.
- I wanted to move usePlugin hook up two levels, so it wont make all call many times. I'll open bug/feature request for that

2023-01-01 10:28 UTC, morhag90 approved these changes

2023-01-13 09:55 UTC, yuval-hazaz commented
@barshimi what is the status of this PR? Let's make sure we merge it if it is ready to be merged... It has sat open for two weeks already while we keep drifting away 
let me know if you want to review that together

2023-01-22 07:57 UTC, yuval-hazaz requested changes
well done! see comments

2023-01-22 07:57 UTC, yuval-hazaz commented on packages/amplication-client/src/Plugins/InstalledPluginSettings.scss
> +    margin-top: 7px;
use param

2023-01-22 07:57 UTC, yuval-hazaz commented on packages/amplication-client/src/Plugins/InstalledPluginSettings.scss
> +      width: 200px;
use local params

2023-01-22 07:57 UTC, yuval-hazaz commented on packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx
> +                            handlePluginInstalledChange(
version change should not be saved automatically - first show the new settings object and the save button will save all changes including the version selection

2023-01-24 10:02 UTC, yuval-hazaz approved these changes

2023-01-24 13:10 UTC, merged