Epic/paywall
amplication/amplication pull request #4767
Opened 2023-01-01 13:11 UTC by EugeneTseitlin

Close: #4527
Close: #4499
Close: #4574

## PR Details

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-01-01 16:18 UTC, morhag90 requested changes

2023-01-01 16:18 UTC, morhag90 commented on packages/amplication-server/src/core/project/project.service.ts
> +  async validateSubscriptionPlanLimitationsForProject(
let's talk about this query

2023-01-01 17:09 UTC, morhag90 commented on packages/amplication-server/src/core/billing/billing.service.ts
> +      await this.stiggClient.waitForInitialization();
Check if there is a way to make this call as a single tone

2023-01-01 17:10 UTC, yuval-hazaz submitted a review, later dismissed

2023-01-01 17:10 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/ResourceList.tsx
> +  const subscription =
instead of using a query, we should be able to get the data from appContext

2023-01-03 12:55 UTC, morhag90 approved these changes

2023-01-03 12:58 UTC, merged