feat(server): add ability to delete project, fixes #4044
amplication/amplication pull request #4981
Opened 2023-01-17 01:07 UTC by MichaelSolati

Close: #4044

## PR Details

- Add a mutation to the project resolver for deleting a project
- Add a method to project service to delete a project
  - First "deletes" all resources belonging to a project
  - Next "deletes" project by renaming it and setting `deletedAt` field
- Add `deleteProjectResources` method to the resource service
  - Gets all resources belonging to a project and then checks if they're empty, also tallies services to update billing
  - Batches mutations of resources and marks them as "deleted"
  - Takes batch and runs it as a transaction (trying to limit Prisma calls)
  - Update billing service based on deleted services
  - Something with deleting git repos... I'd love for someone to look at this and make sure I'm not crazy.
- Update UI to call `deleteProject` mutation

I still need to work on tests and cleaning up some random protections.

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-01-17 02:40 UTC, MichaelSolati commented
Sorry to add so many of y'all for the review, I'm just unsure who's responsible for these files/services/etc

2023-01-17 07:02 UTC, yuval-hazaz requested changes
well done @MichaelSolati 
It is great to see how you followed all the best practices and navigated your way on the code. 

Please see my comments regarding leaving the resources in place

2023-01-17 07:02 UTC, yuval-hazaz commented on packages/amplication-server/src/core/resource/resource.service.ts
> +      );
we may need to keep this code anyway even if we not actually deleting the resources, so maybe you could move it to the "deleteProject" function

2023-01-17 07:02 UTC, yuval-hazaz commented on packages/amplication-server/src/core/resource/resource.service.ts
> +    );
we should keep this data also as it is (for future undo)

2023-01-23 17:12 UTC, MichaelSolati commented
@yuval-hazaz just to secure a solution to the resources. Should we block resources from being queried/modified by making checking the status of the parent project, or should we have a status field on a resource as to what the parent's status is?

I'm inclined to prefer adding a status field to the resource, we could just call it `parentsStatus` and allow it to be `null` or `'deleted'`. Down the road we can add new statuses such as `archived'`.

Let me know what you think.

2023-01-30 07:29 UTC, yuval-hazaz commented
> I'm inclined to prefer adding a status field to the resource, we could just call it `parentsStatus` and allow it to be `null` or `'deleted'`. Down the road we can add new statuses such as `archived'`.

I am OK with adding a new field, but in this case, I prefer to keep it simple and use a boolean with a specific definition - it will hold a boolean value whether the record is effectively active or not. It should hold "false" whether the actual record is deleted or any of its parents is deleted. 

When fetching the data, we should only check for that value. 

we can call the field "EffectiveActive"

2023-02-20 09:25 UTC, abrl91 commented
@MichaelSolati, any progress?

2023-02-20 17:20 UTC, MichaelSolati commented
Working on this today. Should be done in the next day or so.

2023-02-21 18:38 UTC, MichaelSolati commented
I am finished making the requested changes. I don't think the name `effectiveActive` is that clear as to what it represents; I'm wondering if we can rename it to `archived`?

2023-02-22 10:23 UTC, yuval-hazaz commented
> I am finished making the requested changes. I don't think the name `effectiveActive` is that clear as to what it represents; I'm wondering if we can rename it to `archived`?

I think "archived" can work

2023-02-24 01:38 UTC, MichaelSolati commented
@yuval-hazaz ready for review

2023-03-03 04:38 UTC, dulajdilshan reviewed
LGTM

2023-03-05 04:47 UTC, MichaelSolati commented
@abrl91 @yuval-hazaz @tupe12334 

Can someone review this please.

2023-03-06 16:07 UTC, abrl91 commented
It looks good, I'm just wondering what happens when all projects are deleted, I mean, what will happen to the UI?

![image](https://user-images.githubusercontent.com/39680385/223165563-b2eb0046-388a-407e-8a56-0d566a480e45.png)

2023-03-06 16:38 UTC, MichaelSolati commented on packages/amplication-server/src/core/project/project.service.ts
> +    if (this.billingService.isBillingEnabled) {
Beautiful, I'll remove this check then.

2023-03-10 18:08 UTC, abrl91 commented on packages/amplication-server/migration-scripts/install-auth-core-plugin.ts
> +      archived: { not: true },
We already ran this migration script on the DB, so I don't this is relevant.

2023-03-10 18:15 UTC, abrl91 commented
@MichaelSolati, generally, it looks good to me, but I wonder if we want to merge it before fixing the UI issue in case a user deletes all the projects.

As for your question, I am trying to understand. Can you create an issue with more details/examples?

2023-03-10 18:20 UTC, abrl91 approved these changes

2023-03-15 13:35 UTC, yuval-hazaz approved these changes

2023-03-15 13:38 UTC, merged