feat(pr-service): add more clear and exact logs
amplication/amplication pull request #5069
Opened 2023-01-25 13:55 UTC by tupe12334

Partial: #4953 

## PR Details

This pull request is a refactor of our logs to provide more clear feedback for the user

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-01-25 19:53 UTC, abrl91 approved these changes

2023-01-25 19:54 UTC, abrl91 commented
I approved it, but we need to check why it happens. As we saw together, it's not the case every time (that the build doesn't exist)

2023-01-26 07:56 UTC, yuval-hazaz requested changes

2023-01-26 07:56 UTC, yuval-hazaz commented on packages/amplication-git-pull-request-service/src/diff/diff.service.ts
> +  private static assertBuildExist(buildPath: string, buildId: string): void {
```suggestion
  private static validateIfBuildExist(buildPath: string, buildId: string): void {
```

2023-01-26 10:26 UTC, EugeneTseitlin commented
@tupe12334 Please, connect PR to the corresponding issue.

2023-01-29 12:00 UTC, yuval-hazaz approved these changes

2023-01-29 12:00 UTC, merged