Wrong design for project name error
amplication/amplication pull request #5102
Opened 2023-01-31 16:18 UTC by sajdakabir

Close: #4652 

## PR Details

## PR Checklist

- [X] Tests for the changes have been added
- [X] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-02-01 12:14 UTC, overbit requested changes

2023-02-01 12:14 UTC, overbit commented on package-lock.json
> +      "dev": true,
Also these changes to the package-lock are unrelated.

2023-02-01 13:21 UTC, sajdakabir commented
@overbit can you please check it once again?

2023-02-01 15:44 UTC, EugeneTseitlin requested changes
Please, don't delete package-lock.json

2023-02-01 19:42 UTC, sajdakabir commented
Hey, @EugeneTseitlin sorry for this :(. Is it okay now?

2023-02-02 07:55 UTC, yuval-hazaz commented
@sajdakabir thanks for you support.
I just saw that another PR was accepted to resolve this issue (https://github.com/amplication/amplication/pull/5091) 
but, since you were assigned to it, we will accept your PR once it is complete. 
Please also have a look at the solution in https://github.com/amplication/amplication/pull/5091 - and see if you want to use anything from there.

2023-02-07 09:01 UTC, EugeneTseitlin commented
> Hey, @EugeneTseitlin sorry for this :(. Is it okay now?

Still not. Please, revert deleting package-lock.json. You can check the changes in "Files changed" tab. package-lock.json should not be mentioned there.

2023-02-08 04:52 UTC, sajdakabir commented
@EugeneTseitlin can you check now?

2023-02-15 11:53 UTC, EugeneTseitlin commented on .github/workflows/release.template.yml
> +          INPUT_BUILD_ARGS: GIT_REF=${{ github.ref }}
This change is not related to the PR.

2023-02-15 13:04 UTC, EugeneTseitlin commented
@sajdakabir Thank you for the contribution! 
After a deeper look into the issue and consulting with the team, we've came to a conclusion that an actual scope of the issue is wider than we thought and we've decided to review every usage of TextField component and make sure that it's aligned with the design system. We're planning to solve this issue by the team effort, so it's not available for community. We really appreciate your effort, but unfortunately the PR can't be accepted, because our plan has changed. 
We're welcome to PRs from a community, so feel free to request an assignment for another issue with "open for community" tag.
Thanks for being with us!

2023-02-15 13:04 UTC, closed without merging