fix(git-util): rename and replace IGitProvider
amplication/amplication pull request #5128
Opened 2023-02-06 14:09 UTC by tupe12334

Partily: #5113

2023-02-06 14:13 UTC, overbit requested changes

2023-02-06 14:13 UTC, overbit commented on packages/amplication-git-utils/src/IGitProvider.ts
> +export interface IGitProvider {
There is no convention to prefix interfaces in Ts with `I` and we are not currently using this convention elsewhere. Please rename it to `GitProvider`

2023-02-06 15:58 UTC, merged

2023-02-06 16:04 UTC, abrl91 commented
@overbit @tupe12334 
This change doesn't conform to our conventions
[File & Declaration Naming](https://www.notion.so/amplication/File-Declaration-Naming-666afe407ff14ed6aa54bcd3dead45a8)

2023-02-06 16:05 UTC, overbit commented
Good point @abrl91 . Please @tupe12334 rename this

2023-02-06 16:09 UTC, abrl91 commented
@overbit 
It's not only the renaming. All shared types/enums/interfaces should be in the same file. This interface is shared between all providers

2023-02-07 09:59 UTC, tupe12334 commented
I think we need to refactor the notion file because we don't work like that anywhere not even in our generated code