🐛 Bug Report: Wrong design for error with project name #4560
amplication/amplication pull request #5138
Opened 2023-02-07 09:48 UTC by gitstart

###DEMO VIDEO
https://www.loom.com/share/57be56fd96c54edd87e0330ac1fe91af.

2023-02-07 09:53 UTC, gitstart commented
@GreenMachine01 This PR is ready for review. Thanks. cc @EugeneTseitlin

2023-02-11 08:25 UTC, yuval-hazaz submitted a review, later dismissed
Thanks for the fix! I like the way you push the error to the form. We should use this as a common practice (@overbit @abrl91 please have a look) 


Please see one comment to be fixed

2023-02-11 08:25 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/NewProject.tsx
> +        setErrors({ name: ERROR });
Please keep the original error text. The current implementation will display the same error message for all types of errors that can be returned from the server which is not correct 
```suggestion
        setErrors({ name: formatError(err); });
```

2023-02-11 08:25 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/NewProject.tsx
> +        console.error(err);
we can remove this now

2023-02-14 15:56 UTC, gitstart commented
@yuval-hazaz  resolved the comments.

2023-02-15 14:44 UTC, EugeneTseitlin requested changes
Please, make sure that changes are applied only to New Project component. Merge recent changes from our repo and resolve a conflict.
The change in New Project component is fine, I've checked it and it works as expected.

2023-02-20 09:02 UTC, gitstart commented
@EugeneTseitlin  resolved conflicts.

2023-02-20 09:21 UTC, EugeneTseitlin commented
> @EugeneTseitlin conflicts resolved.

There should not be any change in  ISSUE_TEMPLATE, workflows folders.
Changes should be only in NewProject.tsx file.

2023-02-21 05:27 UTC, gitstart commented
> > @EugeneTseitlin conflicts resolved.
> 
> There should not be any change in ISSUE_TEMPLATE, workflows folders. Changes should be only in NewProject.tsx file.

Hey @EugeneTseitlin reverted changes in workflow file. I think it was added somehow when we try to resolve changes between master and next branch

2023-02-22 13:58 UTC, EugeneTseitlin approved these changes

2023-02-22 14:03 UTC, merged