feat(git-utils): add strict null check
amplication/amplication pull request #5152
Opened 2023-02-07 16:05 UTC by tupe12334

This pull request adds a strict null check to protect us from unexpected behavior.

2023-02-09 08:55 UTC, abrl91 requested changes
can you elaborate on why we need all the `| null`?

2023-02-09 10:34 UTC, tupe12334 commented
@abrl91 because those functions can return null so we can show that in the function signature.

2023-02-09 17:45 UTC, overbit approved these changes

2023-02-09 17:45 UTC, overbit commented on packages/amplication-git-utils/src/git/github.service.ts
>      this.privateKey = GITHUB_APP_PRIVATE_KEY;
I like this 💯

2023-02-10 10:51 UTC, abrl91 approved these changes

2023-02-10 10:52 UTC, merged