As User - I want to use a new "Help" menu in the top bar
amplication/amplication pull request #5168
Opened 2023-02-09 15:06 UTC by gitstart

### DEMO_VIDEO
https://www.loom.com/share/54d89adaf7cf4810a4187cc45f33a389

2023-02-11 08:09 UTC, yuval-hazaz requested changes
Thanks for your support! good job!
please fix based on the comments before we can merge

2023-02-11 08:09 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
> +    url: "https://discord.com/channels/757179260417867879/1063337571184279582",
```suggestion
    url: "https://amplication.com/discord",
```

2023-02-11 08:09 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss
> +
@EugeneTseitlin can you please have a look at this?
Do we need all the CSS locally? I expect the styles to be inherited from the component directly from the design system

2023-02-11 08:09 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
> +                    }}
This solution is OK only for the current situation where we have a single item with a callback, but we need to implement a more generic solution.

we can use `itemData` on SelectMenuItem to pass a name of a command and then in a callback function trigger a function based on the command name

{ name: "Contact Us", url: null, itemData: COMMAND_CONTACT_US },

2023-02-16 05:52 UTC, gitstart commented
> Thanks for your support! good job! please fix based on the comments before we can merge

Hi @yuval-hazaz We've resolved 1st and and 3rd feedback, for the 2nd one do we have to do attend to do that feedback ?

2023-02-21 08:11 UTC, yuval-hazaz commented on packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss
> +
@EugeneTseitlin ?

2023-02-21 08:15 UTC, yuval-hazaz approved these changes

2023-03-09 07:38 UTC, merged