Fix/5220 message broker base directory
amplication/amplication pull request #5375
Opened 2023-03-08 19:24 UTC by kabhamo

Issue number: #5220

## PR Details

When the user tried to view the base directories of the Message broker resource an error was thrown `Cannot return null for non-nullable field Query.projectConfigurationSettings`.

The reason behind this error was about using the wrong **Resource Id** which was thrown from `projectConfigurationError` in `useProjectConfigSettingsHook.tsx` hook

By replacing the **Resource id** with `projectConfigurationResource?.id` as the query asks for. The bug was solved.
After doing some tests I figured out that the `updateResourceSettings` query also returns a similar error so I replace the id with the relevant one mentioned at the top. Ended with the GET and UPDATE queries working as wanted.

NOTE: The last commit was about solving some conflicts after updating my branch. 

Waiting for feedbacks :)

2023-03-09 14:53 UTC, morhag90 approved these changes

2023-03-09 14:55 UTC, tupe12334 commented
@kabhamo  Can you please remove the package-lock from this pull request?

2023-03-09 14:57 UTC, tupe12334 requested changes
The logic is working and approved but can you please remove the change of the package-lock before we merge?

2023-03-09 16:47 UTC, tupe12334 commented
@kabhamo  Not removing it, i meant removing the change from the pull request, so that the package-lock will not change

2023-03-10 09:21 UTC, yuval-hazaz approved these changes

2023-03-10 15:26 UTC, merged