feat(git-utils): get repositories
amplication/amplication pull request #5391
Opened 2023-03-09 21:50 UTC by abrl91

part of: #5261 

## PR Details

- get repository
- get repositories

## PR Checklist

- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-03-14 14:34 UTC, overbit commented on packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts
missing unit tests

2023-03-14 14:48 UTC, abrl91 commented on packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts
> +      this.gitProviderArgs.providerOrganizationProperties;
yes, but the refactoring for the refresh token will be implemented in another PR

2023-03-14 14:50 UTC, abrl91 commented on packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts
I am trying to figure out how to write efficient tests for this, as this service communicates with the bitbucket server.

2023-03-15 10:04 UTC, overbit requested changes

2023-03-15 10:05 UTC, overbit approved these changes

2023-03-15 11:18 UTC, merged