refactor(client): refactored  use resource button infos
amplication/amplication pull request #5553
Opened 2023-03-23 14:40 UTC by YAbargil

2023-04-18 09:50 UTC, overbit commented
@YAbargil thanks for the contribution! Can you please update your branch with the latest `next` branch? 
And also remove any package.json versioning changes since we will manage those ourself on release.

2023-04-18 09:50 UTC, overbit requested changes

2023-04-18 09:50 UTC, overbit commented on package.json
@YAbargil thanks for the contribution! Can you please update your branch with the latest next branch?
And also remove any package.json versioning changes since we will manage those ourselves on release.

2023-04-18 09:59 UTC, YAbargil commented on package.json
@overbit  

Someone else PR has already merged for the issue.
see: #5605

2023-04-24 07:39 UTC, overbit commented
https://github.com/amplication/amplication/pull/5605 has been already fixing this issue

2023-04-24 07:39 UTC, closed without merging