solved the ui issues in workspace setting and members section #3654
amplication/amplication pull request #5570
Opened 2023-03-24 18:04 UTC by parthosc

Close: #3654 

## PR Details

fixed the styles of workspace member/setting according to figma file attached in issue

## PR Checklist

- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

![image](https://user-images.githubusercontent.com/51105418/227604899-09ca3fab-5428-4a00-82a0-752a34cde539.png)

2023-03-24 18:04 UTC, parthosc commented
![image](https://user-images.githubusercontent.com/51105418/227605164-4ec50516-8d2e-4958-8343-0c44fcd314d6.png)

2023-03-24 18:05 UTC, parthosc commented
![image](https://user-images.githubusercontent.com/51105418/227605276-e33c30a7-a092-445b-ad1b-c84ac6203c3d.png)

2023-04-18 08:07 UTC, GreenMachine01 commented
@alexbass86 please review the screenshots

2023-04-18 08:12 UTC, GreenMachine01 commented
@souravjain540 see feedback from Alex above.

2023-04-18 08:23 UTC, parthosc commented
@alexbass86 let me check figma design again and set exact size of the icon and other ui

2023-04-18 18:33 UTC, abrl91 requested changes

2023-04-18 18:33 UTC, abrl91 commented on packages/amplication-client/src/Workspaces/MemberListItem.scss
> +    color: #ffbd70;
```suggestion
  @include regular-12
```

I'm unsure about the color, but if what we have in regular-12, is not what you need, you can override it with the color property, just use vars, for example `color: var(--black80);`

2023-04-20 06:30 UTC, morhag90 commented on packages/amplication-client/src/Workspaces/MemberListItem.scss
> +    color: #53dbee;
Please use a var instead:
color: var(--black80); (just an example).

2023-04-30 08:30 UTC, souravjain540 commented
@parthosc  I'd like to offer you some swag for this PR, please make the changes and DM me on Discord :)

2023-05-05 05:09 UTC, parthosc commented
@alexbass86 @souravjain540 

For this [review](https://github.com/amplication/amplication/pull/5570#issuecomment-1512650225), can you confirm that the padding of the `workspace member` ui is different for owner and invited members, I've to make both similar according to figma attached in the issue, right?

2023-05-07 07:04 UTC, alexbass86 commented
> 

yes sir!

2023-05-08 16:07 UTC, parthosc commented
@alexbass86 @souravjain540 
![image](https://user-images.githubusercontent.com/51105418/236873864-63dfcbe4-c0c1-48a2-b2b0-95b420d1d1de.png)

2023-05-09 08:19 UTC, alexbass86 commented
Approved, great job @parthosc. Thank you for the contribution :)

2023-05-10 06:52 UTC, abrl91 approved these changes

2023-05-10 07:03 UTC, merged