fix(data-service-gen): standardize log messages
amplication/amplication pull request #5738
Opened 2023-04-09 20:56 UTC by jatinparmar96

Close: #5283 

## PR Details

This PR adds standardized log messages for the data-service-generator.
Please let me know what other places the logs need to be updated and I can include them in the commits in this PR.

## PR Checklist

- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-04-12 06:59 UTC, overbit requested changes

2023-04-12 06:59 UTC, overbit commented on packages/amplication-server/src/core/build/build.service.ts
@jatinparmar96 thanks for your contribution! From the open issue I can see that there are more logs that need to be updated to increase consistency; can you please review the logs and update when needed?

2023-04-13 14:24 UTC, overbit approved these changes
@jatinparmar96, it's much more complete now, well done!

2023-04-20 07:09 UTC, barshimi approved these changes

2023-04-30 08:51 UTC, souravjain540 commented
@jatinparmar96  I want to give you swag for this PR. can you please DM me your email address on discord?

2023-05-01 09:10 UTC, overbit approved these changes

2023-05-01 09:10 UTC, merged