feat(client): UI for multiple providers
amplication/amplication pull request #5890
Opened 2023-04-28 12:08 UTC by abrl91

Close: #5812

## PR Details
 change the UI to support multiple providers

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-05-05 16:11 UTC, abrl91 commented
Leftovers:
As we can see in the screenshot below -

1. after a connection is established, the state of the git connection status in the footer is not updated
2. the selected group name is probably not saved after a creation/connection to a git repository

![Screenshot 2023-05-05 at 19 04 26](https://user-images.githubusercontent.com/39680385/236509989-1d68acda-4c95-404d-8ef0-58461a3fe567.png)

2023-05-10 15:19 UTC, overbit requested changes

2023-05-10 15:19 UTC, overbit commented on packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.spec.ts
> +          groupName: "my-group",
Always prefer consistency:
either `repositoryName` and `repositoryGroupName` or `name` and `groupName`

2023-05-10 15:19 UTC, overbit commented on packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.spec.ts
> +        groupName: "my-group",
Always prefer consistency:
either `repositoryName` and `repositoryGroupName` or `name` and `groupName`

2023-05-10 15:19 UTC, overbit commented on packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx
> +  console.log("data", data);
Do we need this?

2023-05-10 15:38 UTC, abrl91 commented on packages/amplication-client/src/util/git-git-repository-details.ts
> +  };
There are some places where you still don't have gitOrganization/gitRepository/groupName - so yes - if one of them is not provided, you will get an invalid URL and probably a not found error. 
Do you think we need to add some checks here?

2023-05-10 15:41 UTC, abrl91 commented on packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.tsx
> +    gitRepository?.name
I don't understand. These are not optional parameters

2023-05-10 16:37 UTC, abrl91 commented on packages/amplication-server/src/core/git/git.provider.service.ts
> +      groupName: args.groupName,
I go with name and groupName with all "Repository" related stuff

2023-05-10 16:37 UTC, abrl91 commented on packages/amplication-server/src/core/git/git.provider.service.ts
> +      groupName: args.groupName,
I go with name and groupName with all "Repository" related stuff

2023-05-10 16:50 UTC, overbit approved these changes

2023-05-10 17:36 UTC, abrl91 commented on packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.tsx
> +    gitRepository?.name
I'll create an issue about it

2023-05-10 20:47 UTC, merged