Wizard input fields should be a form
amplication/amplication pull request #5905
Opened 2023-05-04 11:15 UTC by gitstart

### DEMO VIDEO

https://www.loom.com/share/4896a7ba0b6d4c30965825183efb6c98

fixes https://github.com/amplication/amplication/issues/5818

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

2023-06-14 07:29 UTC, yuval-hazaz commented
Thanks for this PR! 

I appreciate the efforts, but I must say I do not like this type of solution where we catch the key down separately on each page
Did you try to think of a more generic solution where the default button in the form is the "Continue" button, and the rest of the logic, including validation is untouched ?

2023-06-14 07:30 UTC, yuval-hazaz requested changes

2023-06-15 14:20 UTC, jaysoni-ash42 commented on packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx
> +
@yuval-hazaz For each step the keyDown event react's differently for input keyDown submits the form whereas for others it updates a state then we move to the continue using tab and hit enter then it submits.

2023-06-16 06:19 UTC, jaysoni-ash42 commented on packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx
> +
@yuval-hazaz  how about using a custom keyEvent wrapper like this 

```
import { ENTER } from "../../../util/hotkeys";

const withKeyboardEvents = (WrappedComponent) => {
  const WithKeyboardEvents = (props) => {
    const handleKeyDown = async (event) => {
      const { key, target } = event;
      if (key === ENTER) {
        if (target.tagName === "INPUT") {
          if (props.formik.validateForm && props.goNextPage) {
            await props.formik.validateForm();
            if (!Object.keys(props.formik.errors).length) {
              props.goNextPage();
            }
          }
        }
        if (target.tagName === "DIV") {
          target.click();
        }
      }
    };

    return <WrappedComponent {...props} onKeyDown={handleKeyDown} />;
  };

  return WithKeyboardEvents;
};

export default withKeyboardEvents;
```
and using this through out the serviceWizard and handling accordingly

2023-06-17 07:16 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx
> +
thanks @jaysoni-ash42 
I will look into it and get back to you ASAP

2023-06-26 21:28 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx
> +
@jaysoni-ash42 after some playing around with this issue, I came up with a new solution that is based on triggering a click on the button (which already incorporates all the logic about validation, etc)
please have a look at this PR I created and let me know what you think
https://github.com/amplication/amplication/pull/6386

Although your solution looks valid, I didn't know how to validate it, so I tried to play with it myself, which eventually brought me to this solution. Thank you so much for the time and effort you spent on this PR.

2023-06-27 03:58 UTC, jaysoni-ash42 commented on packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx
> +
Appreciate @yuval-hazaz  will definitely check out the new pr.

2023-06-28 13:11 UTC, closed without merging