issue #6296, checkmark now shows up on successful build
amplication/amplication pull request #6540
Opened 2023-07-19 23:59 UTC by jeffmchang

## PR Details
This PR only fixes the checkmark, but I will be working on the system returning a build log message in the next PR

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- The current issue is that the panel for the 'Generate Code' is not properly displaying the correct status:

![image](https://github.com/amplication/amplication/assets/109321774/c5faaffb-bc7a-4d2c-b9e0-a7105a2c3d81)

### What is the root cause of that problem?

- The root cause of the problem seems to be coming from BuildSteps.tsx on line 27:

![image](https://github.com/amplication/amplication/assets/109321774/8c30a09e-6a76-4a1f-89dd-dece6cc3de17)

- The `data.build.action.steps.find((step) => step.name === GENERATE_STEP_NAME)` is calling for a `step.name` that is `GENERATE_APPLICATION`

![image](https://github.com/amplication/amplication/assets/109321774/8b6e87d8-5ae6-4877-9618-42f649f4aa20)

- But upon successful completion, the object returns`ADD_TO_QUEUE`:

![image](https://github.com/amplication/amplication/assets/109321774/20c1354f-6448-4010-bc32-61f9869036b9)

### What changes do you think we should make in order to solve the problem?

- Changing `GENERATE_STEP_NAME` to `ADD_TO_QUEUE` leads to the expected result:

![image](https://github.com/amplication/amplication/assets/109321774/e1964c5c-7fd1-4d9d-bbca-2a27f782dd0b)
![image](https://github.com/amplication/amplication/assets/109321774/eb14816a-30fe-4856-b31f-b11de54a7e25)

2023-07-27 18:06 UTC, yuval-hazaz requested changes
Thanks @jeffmchang  for the PR
few comments:
1. In case this PR is fixing an existing issue, please add a reference to an issue number. 
2. Your PR includes changes in package.json and package-lock.json which seems not related to the actual fix. please exclude these changes from the PR. 
3. Your pr includes several unnecessary changes like "console.log" command and other changes. please do not include any changes that are not part of the fix

2023-07-27 18:06 UTC, yuval-hazaz commented on packages/amplication-client/src/VersionControl/BuildSteps.tsx
> +    console.log("DATA STEPS -----------------", data.build.action.steps);
remove this code

2023-07-27 18:06 UTC, yuval-hazaz commented on packages/amplication-client/src/VersionControl/BuildSteps.tsx
> +  console.log("generateCode STATUS-------------", stepGenerateCode);
remove this code

2023-07-27 18:06 UTC, yuval-hazaz commented on packages/amplication-client/src/VersionControl/ActionLog.tsx
> +        {logData.map((stepData, index) => (
why do we need this change?

2023-07-27 18:06 UTC, yuval-hazaz commented on packages/amplication-client/src/VersionControl/BuildSteps.tsx
> +export const GENERATE_STEP_NAME = "ADD_TO_QUEUE";
I am not sure this change is expected, but since I don't see a link to an issue I am not sure what id the goal.

2023-08-18 10:33 UTC, overbit commented
@jeffmchang did you have any time to address @yuval-hazaz comments?

2023-09-28 09:36 UTC, mulygottlieb commented
Thanks for your contribution @jeffmchang !
Unfortunately, since there is no response to the CR comments on this PR, I will close it for now due to inactivity. If you do want to keep working on it and address the comments, feel free to open a new PR and address the comments there. Sorry for the inconvenience.

2023-09-28 09:36 UTC, closed without merging