Fixed Message Broker issue
amplication/amplication pull request #6794
Opened 2023-08-31 08:03 UTC by Sheersendu

Close: #6771 

## PR Details

1. Updated SelectedPatternType with newly selected pattern as by default it was not getting updated instantly.

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-09-14 10:40 UTC, overbit requested changes

2023-09-14 10:40 UTC, overbit commented on packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
@Sheersendu  try to see if there is an easier option. 
i.e. messagePatternsByTopicId useMemo depends on `messagePatterns`, so it might be enough to update that object

2023-09-14 12:31 UTC, Sheersendu commented on packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
Hi @overbit , I agree with you that messagePatternsByTopicId useMemo depends on `messagePatterns`, hence any changes to `messagePatterns` should automatically recompute changes for messagePatternsByTopicId. But I would like to draw your attention towards this [section](https://github.com/amplication/amplication/pull/6794/files#:~:text=%7Btopic%7D-,selectedPatternType%3D%7B,%7D,-onMessagePatternTypeChange%3D%7B)  which is responsible for rendering the updated pattern type, which on debugging I have found out that the value we pass is always `EnumMessagePatternConnectionOptions.None` although `messagePatterns` was being updated, hence not displaying the updated result on the fly. Hence my approach was to recompute selected pattern type before passing at as prop for rendering. 

I'm open for further discussion and improvements😄

2023-09-14 15:34 UTC, overbit commented on packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
Good point. I'd need some help from our wizard @barshimi
What do you think about this change?

2023-09-16 13:19 UTC, Sheersendu commented on packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
Hi @overbit, do we have any updates? Kindly let me knows required changes if any 😄

2023-10-01 11:53 UTC, GreenMachine01 commented
@barshimi @overbit What's the status with this one?

2023-10-02 10:46 UTC, overbit commented on packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
As we got now answer, I'll approve this PR

2023-10-02 10:46 UTC, overbit approved these changes

2023-10-02 10:47 UTC, merged