feat: add documentation link for importing prisma schema
amplication/amplication pull request #7001
Opened 2023-09-25 13:20 UTC by iamshabell

Close: #6826

## PR Details

This pull request adds the following changes:

- Added instruction text with a link to the documentation below the import box.
- Clicking the "Documentation" link now opens the documentation in a new tab.

![Screenshot 2023-09-25 at 4 05 31 PM](https://github.com/amplication/amplication/assets/91321698/00f3296a-4ef7-435c-8440-633f60fd45b0)

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2023-10-02 04:13 UTC, souravjain540 commented
@iamshabell, thanks for the PR. For the next time, please don't start working on issues without getting them assigned to you.

can you please leave a comment in the issue so that i can assign it to you

2023-10-02 04:15 UTC, iamshabell commented
> @iamshabell, thanks for the PR. For the next time, please don't start working on issues without getting them assigned to you.
> 
> can you please leave a comment in the issue so that i can assign it to you

Really sorry about that, here is the issue: https://github.com/amplication/amplication/issues/6826

2023-10-02 15:06 UTC, overbit approved these changes

2023-10-03 05:40 UTC, yuval-hazaz requested changes

2023-10-03 05:40 UTC, yuval-hazaz commented on packages/amplication-client/src/Entity/ImportPrismaSchema/EntitiesImport.scss
> +      color: var(--dark-secondary-turquoise);
@iamshabell thanks for your contribution.
We recently pushed a big UI change to the 'next' branch which may impact your PR. 
Please pull the recent changes from `next` into your branch and make sure you use the latest CSS variables and components.

2023-10-11 10:30 UTC, mulygottlieb approved these changes

2023-10-12 07:40 UTC, merged