ADDED:  A generated service in HTTPS and/or HTTP mode.
amplication/amplication pull request #7369
Opened 2023-11-01 18:09 UTC by xonx4l

issue-:#7364

2023-11-04 13:59 UTC, yuval-hazaz commented
@overbit @mulygottlieb please have a look

2023-11-04 14:20 UTC, overbit requested changes

2023-11-04 14:20 UTC, overbit commented on packages/amplication-server/src/main.ts
> +    console.log(`HTTP server is running on port ${port}`);
Please use Nestjs logger instead of console.log.

More details here https://docs.nestjs.com/techniques/logger#dependency-injection

2023-11-04 14:20 UTC, overbit commented on packages/amplication-server/src/main.ts
> +    console.log("HTTPS server is running on port 443");
Please use Nestjs logger instead of console.log.

More details here https://docs.nestjs.com/techniques/logger#dependency-injection

2023-11-04 14:20 UTC, overbit commented on packages/amplication-server/src/main.ts
> +  const appMode = process.env.APP_MODE || "http";
Please add the new expected environment variable to the .env file.

2023-11-04 14:20 UTC, overbit commented on packages/amplication-server/src/main.ts
> +    httpsServer.listen(443);
Users might still need to customise the port and as there is a variable for it `process.env.PORT`, the code should use that value, and if missing, default to 443

2023-11-04 14:20 UTC, overbit commented
@xonx4l please maintain the pull request description in line with the template amplication offers

2023-11-04 14:23 UTC, overbit commented
@xonx4l please maintain the pull request description in line with the template amplication offers


@yuval-hazaz @mulygottlieb should we offer this as a plugin instead so the default generated code is slimmer? Many users do TLS termination at higher levels like in load balancer or ingress

2023-11-10 18:07 UTC, xonx4l commented
@overbit  made some changes as per your suggestions . Thanks .

2023-11-17 16:10 UTC, overbit commented
@xonx4l after a discussion internally to the team we decided that having a new plugin that will change the default TLS termination to be at the service level.
Would you be happy to work on such a plugin? The generated code will match what you have here.

2023-11-18 10:23 UTC, xonx4l commented
@overbit  yeah  man I will love to build one .

2023-11-27 10:40 UTC, mulygottlieb commented
@overbit @xonx4l  - I am closing this PR based on the fact we want to add this as a plugin.
@xonx4l  you are welcome to continue the work as a plugin as per the above. Just please note that the changes you suggested here seem to relate to our services while the requested changes are for the **generated code**

2023-11-27 10:40 UTC, closed without merging