feat: add proper info while repository naming
amplication/amplication pull request #7796
Opened 2024-01-12 23:09 UTC by Shurtu-gal

Fixes: #6051 

## PR Details

This PR adds proper information while naming repositories.

![image](https://github.com/amplication/amplication/assets/100484401/4a8bcf3d-9203-4372-bd0d-9cf507000e99)

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2024-01-13 07:21 UTC, yuval-hazaz requested changes

2024-01-13 07:21 UTC, yuval-hazaz commented on libs/util/git/src/git.constants.ts
> +export const REPO_NAME_TAKEN_ERROR_MESSAGE = "Repository is already existing.";
```suggestion
export const REPO_NAME_TAKEN_ERROR_MESSAGE = "Repository already exists.";
```

2024-01-13 07:21 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.scss
> +    font-size: 10px;
dont use fixed numbers, instead use variable when needed.
In this case, it is better to use the <Text component with the relevant textStyle and textColor properties.
see this for example
https://github.com/amplication/amplication/blob/12f27b00c2a05b3f5456439a235c9080ae5a80c1/packages/amplication-client/src/Resource/OverviewSecondaryTile/OverviewSecondaryTile.tsx#L35C22-L35C22

2024-01-13 07:21 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
> +              <p className={`${CLASS_NAME}__info__emphasis`}>
see my comments on the css file and use <Text> instead

2024-01-13 07:21 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/WizardGitCreateRepo.tsx
> +          <p className={`${CLASS_NAME}__info__emphasis`}>
see my comments on the css file and use instead

2024-01-13 07:44 UTC, Shurtu-gal commented
After changes :- 
![image](https://github.com/amplication/amplication/assets/100484401/74a06968-a1f8-4514-b3af-a571f2c347e6)

2024-01-13 07:50 UTC, yuval-hazaz requested changes

2024-01-13 07:50 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
> +                <b>{processGitRepositoryName(values.name)}.</b>
use EnumTextWeight instead of <b> (or just remove it entirely, maybe we don't need to add bold and color together)

2024-01-13 07:50 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
> +                  "The repository name can only contain ASCII letters, digits, and the characters ., -, and _."
move to const at the top of the file

2024-01-13 07:50 UTC, yuval-hazaz commented on packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/WizardGitCreateRepo.tsx
> +          </Text>
same as above

2024-01-14 06:35 UTC, yuval-hazaz approved these changes

2024-01-14 09:40 UTC, merged