chore(devops): attempt initial configuration for local DSG dockerfile
amplication/amplication pull request #7848
Opened 2024-01-21 16:05 UTC by mulygottlieb

Close: #[issue-number]

## PR Details

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2024-02-02 15:29 UTC, yuval-hazaz approved these changes

2024-02-02 15:30 UTC, yuval-hazaz commented
@overbit can you also review this please?
@mulygottlieb are we ready to push this to next ?

2024-02-02 15:52 UTC, overbit commented
The changes in general look good. 
The only downside is that it won't force contributor to create separate PR for deployable as it won't require packages to be published first.
We need to remember that it's a monorepo and not a monolith.

2024-02-02 15:58 UTC, overbit requested changes

2024-02-02 15:58 UTC, overbit commented on packages/data-service-generator/scripts/package-container.sh
> +    npx nx internal:package:container data-service-generator --dev
`--dev` is an invalid option. Only production configuration has the alias `--prod`

```suggestion
    npx nx internal:package:container data-service-generator --configuration dev
```

2024-02-06 09:21 UTC, overbit approved these changes

2024-02-23 13:08 UTC, merged