feat(client): add apply changes confirmation dialog BTM
amplication/amplication pull request #7997
Opened 2024-02-13 14:45 UTC by morhag90

Close: #7883 

## PR Details

 Add the apply changes confirmation dialog after re-entering the architecture tab. 
## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

2024-02-13 15:08 UTC, yuval-hazaz requested changes

2024-02-13 15:08 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx
> +
Use a new component <ModelOrganizerChangesExistConfirmation/> and move all the logic including the useState and messages to it to keep the parent component lean

2024-02-13 15:08 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx
> +  ] = useState<Date>(null);
why do we need two useStates?

2024-02-13 17:23 UTC, yuval-hazaz requested changes
you need to set the state to false otherwise the message will pop after doing the first change because the state is still null

2024-02-13 17:23 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/ApplyChangesConfirmationModelOrganizer.tsx
> +    if (
else set(false)

2024-02-13 17:23 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/ApplyChangesConfirmationModelOrganizer.tsx
> +  const [confirmApplyChangesDialog, setConfirmApplyChangesDialog] = useState<
showDialog
```suggestion
  const [showDialog, setShowDialog] = useState<
```

2024-02-13 17:23 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/ApplyChangesConfirmationModelOrganizer.tsx
> +const ApplyChangesConfirmationModelOrganizer = ({ changes }: Props) => {
```suggestion
const ModelOrganizerPreviousChangesExistConfirmation = ({ changes }: Props) => {
```

2024-02-20 14:58 UTC, overbit approved these changes

2024-02-25 09:37 UTC, mulygottlieb approved these changes

2024-02-25 09:40 UTC, merged