Feat/7966 search BTM => Improve search: add search entities and highlight the results
amplication/amplication pull request #8012
Opened 2024-02-15 15:57 UTC by morhag90

Close: #7966 

## PR Details

Improve search: add search entities and highlight the results.
## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

2024-02-17 09:22 UTC, yuval-hazaz requested changes

2024-02-17 09:22 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/types.ts
> +  highlight: boolean;
make this param options
```suggestion
  highlight?: boolean;
```

2024-02-17 09:22 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/helpers.ts
> +        highlight: false,
we dont have to add this after we make the property optional

2024-02-17 09:22 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/helpers.ts
> +      highlight: false,
we dont have to add this after we make the property optional

2024-02-17 09:22 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx
> +        const searchModelGroupNodes = nodes.filter((node) =>
these are not just modelGroupNodes
```suggestion
        const searchResults = nodes.filter((node) =>
```

2024-02-17 09:22 UTC, yuval-hazaz commented on packages/amplication-client/src/Project/ArchitectureConsole/nodes/modelGroupNode.tsx
> +  EnumTextColor,
can be removed

2024-02-18 10:02 UTC, mulygottlieb approved these changes
Approved, comments by Yuval were addressed.

2024-02-18 10:06 UTC, merged