Fix/8691
amplication/amplication pull request #8692
Opened 2024-06-19 13:07 UTC by morhag90

Close: #8691

## PR Details

Add to Jovu createFields function validation for lookup field creation. 
## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

2024-06-19 13:23 UTC, yuval-hazaz requested changes

2024-06-19 13:23 UTC, yuval-hazaz commented on packages/amplication-server/src/core/assistant/assistantFunctions.service.ts
> +            return {
add the field name so jovu can link the error to the specific field

2024-06-23 09:53 UTC, mulygottlieb approved these changes

2024-06-23 10:02 UTC, yuval-hazaz approved these changes

2024-06-23 10:10 UTC, merged